name: Backend Build

on:
  push:    
    branches:      
      - main  
  pull_request:    
    branches:      
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: '1.0'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:          
        distribution: 'adopt'          
        java-version: '16'

    - name: Build with Maven
      working-directory: backend
      run: mvn package -DskipTests=true -Dversion.application=${APP_VERSION}.${GITHUB_SHA:0:7}

    - name: Integration tests
      working-directory: backend
      run: mvn test

    - name: Run Checkstyle
      working-directory: backend
      run: mvn checkstyle:checkstyle

    - name: Run SpotBugs
      working-directory: backend
      run: mvn spotbugs:check
      continue-on-error: true

    - name: Upload Backend Archive
      uses: actions/upload-artifact@v4
      with:
        name: backend-archive
        path: backend/target/*.jar

    - name: Upload Reports Archives
      uses: actions/upload-artifact@v4
      with:
        name: reports-archive
        path: |
          backend/target/surefire-reports/
          backend/target/checkstyle-result.xml
          backend/target/spotbugsXml.xml 
