name: Frontend Build

on:
  push:    
    branches:      
      - main  
  pull_request:    
    branches:      
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: '1.0'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:          
        node-version: '16'

    - name: Build with NPM
      working-directory: frontend  
      run: |
        npm install
        npm run build

    - name: Create Archive
      working-directory: frontend
      run: tar -czvf sausage-store-${APP_VERSION}.${GITHUB_SHA:0:7}.tar.gz -C dist/frontend .

    - name: Upload Frontend Archive
      uses: actions/upload-artifact@v3
      with:
        name: frontend-archive
        path: frontend/sausage-store-*.tar.gz
